# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b40bf8907b2ee464ddccdee2334e80a2a3e21089d8656a101cef1c5b43676763639c788033687a3e1ae8a311d443791a378ad981dd4055d1aa6176ec2667ebc5

test:
  secret_key_base: d48b5bba95949c4fff1b6697208f70e9699a6288656e7ef38b3bd6968b2282f4f4e863c0edfafa77aea357e7f30905018de1ee7e820c9557e35e7d16e0097b20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
